### ISSUE TITLE
Met error when compressing images.

### ISSUE THREAD

**Issue by ulivz** [dong4j/markdown-image-kit#1]
Hi, thanks for the plugin, I just met a error when I tried to compress images:

![image](https://user-images.githubusercontent.com/23133919/59160768-4b421080-8b0c-11e9-8007-8bda325c5422.png)

Could you help me? Thanks!

---

BTW, how should I use baiduYun as OSS?

**Comment by dong4j** [comment]
Sorry, I will deal with this problem as soon as possible. When I find a job, I will complete the planned map as soon as possible.

**Comment by dong4j** [comment]
- What is your version of the idea? 
- What is the operation of compressing the image? 
- What is the format of the image? png?

BOS expected to be supported in version 0.0.4

**Comment by dong4j** [comment]
new version 1.2.0 is available, add Baidu BOS.
Thanks for feedback.
