### ISSUE TITLE
Android Studio 4.1.1 版本 JavaFX WebView

### ISSUE THREAD

**Issue by javakam** [dong4j/markdown-image-kit#12]
`Android Studio 4.1.1` 👉 `Tried to use preview panel provider (JavaFX WebView), but it is unavailable. Reverting to default.`

![image](https://user-images.githubusercontent.com/15343661/105138687-34f59680-5b30-11eb-9b71-1cb454394cfe.png)

**Comment by dong4j** [comment]
这个是 JetBrains Markdown 的问题, 你可以参考下面的链接解决这个问题, 谢谢你的反馈.

https://stackoverflow.com/questions/64433280/preview-panel-provider-javafx-webview-error-after-android-studio-update
