### ISSUE TITLE
建议添加一个CHANGELOG.md的更新日志

### ISSUE THREAD

**Issue by wltj920** [dong4j/markdown-image-kit#13]
最近作者更新了好多次，但不知道具体更新了啥，能否添加更新日志？类似于下面这种

## 1.6.2 \[2021-02-22]
* 更新了XXX
* 修复了XXX

**Comment by dong4j** [comment]
请看 idea plugin 的更新说明, 或者 https://github.com/dong4j/markdown-image-kit/blob/feature/1.6.2/includes/pluginChanges.html.

后面这个仓库我再加一个 changelog.md
