### ISSUE TITLE
自定义图床怎么设置？

### ISSUE THREAD

**Issue by bmxbmx3** [dong4j/markdown-image-kit#6]
比如我想在vultr配置chevereto自建一个图床，这时怎么配置自定义图床？

**Comment by dong4j** [comment]
自定义图床暂时还未实现, 不好意思
在 2019年11月11日 +0800 AM12:25，bmxbmx3 <notifications@github.com>，写道：

**Comment by xugaoxiang** [comment]
imgUrl和imgur是同一个东西吗？

**Comment by dong4j** [comment]
> imgUrl 和 imgur 是同一个东西吗？

不是哦, [imgUrl](https://github.com/helloxz/imgurl), [imgur](https://mashable.com/category/imgur/)

**Comment by dong4j** [comment]
自定义图床以实现
