### ISSUE TITLE
粘贴的时候好像只能复制到本地，不会上传到sm.ms

### ISSUE THREAD

**Issue by ty-peng** [dong4j/markdown-image-kit#8]
IDEA 2020.1

插件版本0.0.3

![image](https://user-images.githubusercontent.com/20200179/79549675-e101e100-80c9-11ea-9887-d2b307f9c082.png)

之前有勾选`上传图片并替换`选项

ps: 刚才下载了0.0.4版本的插件release无法安装，提示`Fail to load plugin descriptor from file markdown-image-kit-0.0.4.zip`

**Comment by dong4j** [comment]
如果是 2020.1 版本, 需要先把自带的 markdown 禁用, 安装后再开启自带的 markdown.
sm.ms 的 API 已修改, 还未适配, 将在下一个版本完成.

**Comment by ty-peng** [comment]
> 如果是 2020.1 版本, 需要先把自带的 markdown 禁用, 安装后再开启自带的 markdown.
> sm.ms 的 API 已修改, 还未适配, 将在下一个版本完成.

ok
